project:
  type: website
  output-dir: docs

website:
  title: "Avalanche Risk Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: A1_Report_Final_Draft_html.qmd
        text: Paper
      - href: LLMs_Statement.qmd
        text: AI Statement
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
