project:
  type: website
  output-dir: docs

website:
  title: "Avalanche Risk Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - A1_Report_Final_Draft_html.qmd
      - LLMs_statement.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
